trigger:
  branches:
    include:
      - main

pool: yarb

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo "##vso[task.setvariable variable=imageTag]$(Build.BuildId)"
    echo "##vso[task.setvariable variable=latestTag]latest"
  displayName: 'Set Image Tags'

- task: Docker@2
  displayName: 'Build and Push Docker Image with Unique Tag'
  inputs:
    containerRegistry: 'dockerhub'
    repository: 'youssefabu/media-network-expressjs'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(imageTag)

- task: Docker@2
  displayName: 'Tag and Push Docker Image with Latest Tag'
  inputs:
    containerRegistry: 'dockerhub'
    repository: 'youssefabu/media-network-expressjs'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(latestTag)
    arguments: '--tag $(containerRegistry)/$(repository):$(latestTag)'
