apiVersion: v1
kind: ConfigMap
metadata:
  name: express-config
  namespace: backend
data:
  SECRET: "Thisismysecret"
  MONGO_DB_HOST: "mongo-svc"
  MONGO_DB_PORT: "27017"
  MONGO_DB_PARAMETERS: "?authSource=contacts-system"
  MONGO_DB_DATABASE: "contacts-system"
