apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: express-hpa
  namespace: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: express-deployment
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
